cognite/src/api/api_client.rs, cognite/src/api/authenticator.rs, cognite/src/auth.rs, cognite/src/cognite_client.rs, cognite/src/lib.rs, cognite/src/retry.rs
Add the authenticator to middleware instead of appending it on each request.
This has the advantage of letting us retry 401s sometimes, which is useful.
=> Auth middleware

cognite/src/cognite_client.rs, cognite/src/error.rs
A slightly more flexible approach, to avoid constantly adding new constructors, or breaking existing constructors.
This PR also adds the ability to pass a reqwest client externally.
=> Client builder

cognite/src/api/authenticator.rs
This lets custom auth implementations report failures the same way the
built-in ones do.
=>  Let custom auth return Results

cognite/Cargo.toml, cognite/src/dto/core/sequences.rs, cognite/src/dto/data_organization/relationships.rs, cognite/src/dto/iam/security_category.rs
This is holding up the renovate PRs.
I also found that uuid was unused.
=> Fix new clippy warnings from 1.68

cognite/src/api/resource.rs
We need to check for empty create and update arrays when upserting, otherwise the request will fail
=> Fix upsert

cognite/Cargo.toml, cognite/src/api/data_modeling/instances.rs, cognite/src/api/data_modeling/mod.rs, cognite/src/api/mod.rs, cognite/src/api/resource.rs, cognite/src/cognite_client.rs, cognite/src/dto/data_modeling/instances.rs, cognite/src/dto/data_modeling/mod.rs, cognite/src/dto/mod.rs, cognite/src/lib.rs, cognite/tests/asset_tests.rs, cognite/tests/common/mod.rs, cognite/tests/datapoints_tests.rs, cognite/tests/event_tests.rs, cognite/tests/file_tests.rs, cognite/tests/fixtures/mod.rs, cognite/tests/instances_tests.rs, cognite/tests/time_serie_tests.rs
Minimal implementation of the DMSv3 `models/instances` endpoint.
Changes: 
- Added create, list, delete, retrieve (minimal) for instances.
- Added DTOs for instances, following the [openapi spec](https://cog.link/dmsv3) as much as possible (naming, etc)
- Tests for the endpoint use a mock server: in order to properly test w.r.t. CDF we also need the `spaces` and `views` endpoints (to-do)
=> Add models/instances endpoints

README.md, cognite/src/api/resource.rs, cognite/src/dto/core/asset/filter.rs, cognite/src/dto/core/asset/mod.rs, cognite/src/dto/core/datapoint/filter.rs, cognite/src/dto/core/event/filter.rs, cognite/src/dto/core/event/mod.rs, cognite/src/dto/core/files/file.rs, cognite/src/dto/core/files/filter.rs, cognite/src/dto/core/sequences.rs, cognite/src/dto/core/time_serie/filter.rs, cognite/src/dto/core/time_serie/mod.rs, cognite/src/dto/data_ingestion/extpipes.rs, cognite/src/dto/data_ingestion/raw.rs, cognite/src/dto/data_modeling/common.rs, cognite/src/dto/data_organization/datasets.rs, cognite/src/dto/data_organization/labels.rs, cognite/src/dto/data_organization/relationships.rs, cognite/src/dto/filter_types.rs, cognite/src/dto/iam/group.rs, cognite/src/dto/iam/security_category.rs, cognite/src/dto/iam/session.rs, cognite/src/dto/items.rs, cognite/src/dto/patch_item.rs
- Use skip_serialize_none for cleaner code
- Use From\<T\> instead of From<&T> for conversions. It is good practice to leave the cloning to the user.
=> Misc cleanup and fixes

cognite/Cargo.toml, cognite/src/dto/data_modeling/data_models.rs, cognite/tests/instances_tests.rs
The [retrieve data models endpoint](https://api-docs.cognite.com/20230101/tag/Data-models/operation/byExternalIdsDataModels) does not require the `version` field in the request, so I believe it should be optional in the `DataModelId` as well.
(This PR also includes fixes for some minor `cargo clippy` warnings.)
=> Make "version" field of DataModelId optional

cognite/src/api/api_client.rs, cognite/src/api/authenticator.rs, cognite/src/cognite_client.rs
- Make the request method POST. It's what we use elsewhere, and it seems to be more generally accepted.
- Log the raw error message if it fails to deserialize.
- Expose the HTTP client we use, to make it easier to reuse the authentication.
=> Improve authenticator ergonomics

cognite/Cargo.toml, cognite/src/api/api_client.rs, cognite/src/api/utils.rs, cognite/src/cognite_client.rs, cognite/src/error.rs, cognite/tests/file_tests.rs
Errors were doing a lot they didn't need to. This makes them more consistent, and also prefers anyhow::Error over String in a few cases where it is possible to capture more error context.
=> Make errors less messy

cognite/Cargo.toml
Don't bring in openssl feature with reqwest crate.
Bringing in openssl forces us to link against it in the monorepo, which we would prefer to avoid.
=> Remove openssl feature from reqwest

README.md, cognite/README.md, cognite/src/lib.rs
The `cognite` crate should be self-contained, but it was referring to the README.md in the workspace. 
The README should be in the crate itself. Split up the README into a user-facing README in `cognite`, and a more developer oriented README in the workspace.
Context for this change: https://cognitedata.slack.com/archives/C03U0JKUEQZ/p1706597740067559?thread_ts=1706519213.544409&cid=C03U0JKUEQZ
=> Split out README for users (to cognite/) and devs

cognite/src/api/core/time_series.rs
Helps improve resiliency when making multiple requests in parallel.
=> Ignore duplicates when creating missing time series

cognite/src/api/core/assets.rs, cognite/src/api/core/events.rs, cognite/src/api/core/files.rs, cognite/src/api/core/sequences.rs, cognite/src/api/core/time_series.rs, cognite/src/api/data_ingestion/raw.rs, cognite/src/api/data_modeling/containers.rs, cognite/src/api/data_organization/datasets.rs, cognite/src/api/data_organization/relationships.rs, cognite/src/api/iam/sessions.rs, cognite/src/api/resource.rs, cognite/src/dto/items.rs
There are multiple different types (`Items`, `ItemsWithCursor`, `ItemsWithoutCursor`, `ItemsWithIgnoreUnknownIds`) that all represent the same basic structure: `{"items":[...], ...}`. The reduce code duplication, I'm proposing that this is changed to have a single base type (`Items`) which is generic enough to work with all of these cases:
```
#[derive(Copy, Clone, Debug, Default, Serialize, Deserialize)]
pub struct Items<C, E = ()> {
pub items: C,
#[serde(flatten)]
pub extra_fields: E,
}
```
The `items` field should be a collection of items, such as `Vec<T>` or `&[T]`.
The `extra_fields` field can be used to extend the list object with additional fields. In this PR, two additional types are defined for this purpose: `Cursor`, which adds the `nextCursor` field, and `IgnoreUnknownIds`, …
=> Unify into a single Items type

cognite/src/api/api_client.rs, cognite/src/api/resource.rs, cognite/src/dto/core/asset/filter.rs, cognite/src/dto/core/event/filter.rs, cognite/src/dto/core/files/filter.rs, cognite/src/dto/core/time_series/filter.rs, cognite/src/dto/data_ingestion/raw.rs, cognite/src/dto/data_modeling/containers.rs, cognite/src/dto/data_modeling/data_models.rs, cognite/src/dto/data_modeling/views.rs, cognite/src/dto/iam/group.rs, cognite/src/dto/iam/security_category.rs, cognite/src/dto/iam/session.rs, cognite/src/dto/params.rs
By [convention][1], traits and methods taking `owned -> owned` should be named `into_*`, whereas `as_*` should be used for traits and methods taking `borrowed -> borrowed` and `to_*` for taking `borrowed -> borrowed/owned`. Additionally, it is common for single-method traits to have the same name for the method and trait.
For this reason, I propose to rename `AsParams` into `IntoParams` and `AsParams::to_tuples` into `IntoParams::into_params`.
Additionally, to enable usage of custom parameters in `ApiClient` (such as [`ApiClient::get_with_params`][2]) without defining a custom type on usage, I propose adding an implemention of `IntoParams` for `Vec<(String, String)>`.
---
As this is a breaking change, the version of this SDK should be bumped after merging. As this is also the case the …
=> Rename AsParams->IntoParams and add impl for Vec

cognite/src/api/resource.rs, cognite/src/dto/core/asset/mod.rs, cognite/src/dto/core/event/mod.rs, cognite/src/dto/core/files/file.rs, cognite/src/dto/core/sequences.rs, cognite/src/dto/core/time_series/mod.rs, cognite/src/dto/data_ingestion/extpipes.rs, cognite/src/dto/data_organization/datasets.rs, cognite/src/dto/data_organization/relationships.rs, cognite/src/dto/params.rs, cognite/src/dto/patch_item.rs, cognite/tests/asset_tests.rs, cognite/tests/event_tests.rs
Makes it so that we use `add` instead of `set` optionally when updating metadata or labels.
This is breaking, but done in such a way that further breaking changes should be unnecessary.
=> Options for upsert

.github/workflows/build-and-test.yml, cognite/Cargo.toml, cognite/tests/asset_tests.rs, cognite/tests/data_model_tests.rs, cognite/tests/datapoints_tests.rs, cognite/tests/event_tests.rs, cognite/tests/file_tests.rs, cognite/tests/time_series_tests.rs
Tests that contributors might not be setup to run locally now require the feature 'integration-tests' to be set.
=> Use a feature for integration tests

cognite/src/api/core/assets.rs, cognite/src/api/core/files.rs, cognite/src/api/core/time_series.rs, cognite/src/api/data_organization/relationships.rs, cognite/src/api/resource.rs, cognite/src/api/utils.rs, cognite/src/dto/core/datapoint.rs, cognite/src/dto/core/datapoint/proto/data_point_insertion_request.proto, cognite/src/dto/core/datapoint/proto/data_point_list_response.proto, cognite/src/dto/core/datapoint/proto/data_points.proto, cognite/src/dto/data_modeling/instances.rs, cognite/src/dto/data_modeling/views.rs, cognite/src/dto/identity.rs, cognite/src/dto/utils.rs, cognite/src/error.rs, cognite/tests/fixtures.rs
This is a little breaking, since it changes some types. `insert_datapoints_create_missing` also won't work with this until we somehow implement the "create missing" part with DMS time series.
=> Update datapoint protos to add instance ID

cognite/src/api/authenticator.rs, cognite/src/cognite_client.rs
Technically the OAuth 2.0 RFC doesn't require expires_in to be set, so we should let users specify a fallback expiration time.
This also avoids using systemtime, which is unreliable, and instead uses Instant / Duration, which on many operation systems are based on the monotonic clock instead of system time.
=> Allow setting a default token expiry

cognite/src/api/core/time_series.rs, cognite/src/dto/core/datapoint.rs, cognite/src/dto/core/datapoint/status_code.rs, cognite/tests/datapoints_tests.rs
Three major issues:
- Ser/deser for StatusCode was auto-impld, which didn't make sense for how it was used. Better that we serialize/deserialize to the CDF JSON represenetation.
- We didn't properly deserialize Infinity and NaN from double values.
- The untagged enum stuff doesn't work well, there appears to be some bug here, but for latest we actually have sufficient context (using isString) to pick which type to deserialize.
=> Implement ser/deser for StatusCode

cognite/Cargo.toml, cognite/examples/instances/main.rs, cognite/src/dto/data_modeling/instances/extensions/common.rs, cognite/src/dto/data_modeling/instances/extensions/files.rs, cognite/src/dto/data_modeling/instances/extensions/timeseries.rs, cognite/src/dto/data_modeling/instances/extensions/units.rs, cognite/tests/data_models_tests.rs, cognite/tests/file_tests.rs, cognite/tests/time_series_tests.rs
It turns out that the name in `CogniteDescribable` is also optional.
=> clean up of optional values

cognite/src/api/core/time_series.rs, cognite/src/dto/core/datapoint/filter.rs, cognite/src/dto/core/time_series.rs, cognite/src/dto/identity.rs, cognite/src/dto/params.rs, cognite/tests/datapoints_tests.rs
Also improve ergonomics of the IdentityOrInstance type. From and PartialEq impls can really make a type easier to use, and is worthwhile for a core type such as this.
=> Add instance ID to a few timeseries methods

cognite/src/dto/data_modeling/instances.rs, cognite/tests/fixtures.rs, cognite/tests/instances_tests.rs
EdgeDefinition currently has `version: String` causing retrieval of edges with properties to fail.
Changing it to i32 which is the type used in `SlimNodeDefinition`, `SlimEdgeDefinition` and `NodeDefinition`.
=> Correcting datatype of version field in EdgeDefinition dto

cognite/src/api/authenticator.rs, cognite/src/auth.rs, cognite/src/dto/core/datapoint/status_code.rs
There isn't a ton we can do to make it obvious what went wrong, since we can't really log the response from an OAuth request, but we can at least make it obvious that the error came from the authenticator. Currently you'll just get "Error in middleware: Failed to deserialize" which is less helpful.
=> Make error in authenticator a little clearer

cognite/src/dto/data_modeling/common.rs, cognite/src/dto/data_modeling/containers.rs, cognite/src/dto/data_modeling/views.rs, cognite/tests/views_tests.rs
There have been changes to the API, and there was an issue on reverse direct relation properties that somehow slipped by. I've added a test that retrieves a complex view.
=> Add some missing properties to views and containers

cognite/src/api/api_client.rs, cognite/src/api/data_modeling.rs, cognite/src/api/data_modeling/streams.rs, cognite/src/api/request_builder/builder.rs, cognite/src/dto/data_modeling.rs, cognite/src/dto/data_modeling/streams.rs, cognite/src/lib.rs, cognite/tests/records_tests.rs
We were asked not to integration test create/delete for the time being, as there are limits on the number of soft-deleted streams, which we would run into.
This required some very minor changes to core functionality, since we didn't actually have a way to set the cdf-version header. I think the solution is pretty neat.
=> Add support for data modeling streams

Cargo.toml, cognite-codegen/Cargo.toml, cognite/Cargo.toml
As of Rust 1.87, CI fails because of the `large_enum_variant` lint.
<details><summary>Expand to see warnings</summary>
```
warning: large size difference between variants
--> cognite/src/dto/data_modeling/query.rs:170:1
|
170 | / pub enum QueryTableExpression {
171 | |     /// Query nodes.
172 | |     Node(QueryNodeTableExpression),
| |     ------------------------------ the second-largest variant contains at least 336 bytes
173 | |     /// Query edges.
174 | |     Edge(QueryEdgeTableExpression),
| |     ------------------------------ the largest variant contains at least 632 bytes
175 | |     /// Perform complex operations on other query results.
176 | |     SetOperation(QuerySetOperationTableExpression),
177 | | }
| |_^ the entire enum is at least 632 bytes
|
= help: for further …
```
=> Disable large_enum_variant lint
